#:schema https://json.schemastore.org/pyproject.json

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mandr"
description = "..."
version = "0.1.0"
dependencies = [
  "Flask",
  "altair",
  "diskcache",
  "jinja2",
  "markdown",
  "pandas",
  "rich",
  "scikit-learn",
  "srsly",
]

[tool.hatch.build.targets.wheel]
packages = ["mandr"]
